services:
  luigi:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: jetshift:latest
    container_name: jetshift
    ports:
      - "${APP_PORT}:8080"
      - "${LUIGI_PORT}:8082"
    volumes:
      - .:/app:delegated
    networks:
      - default
    environment:
      - APP_PORT=${APP_PORT}
      - LUIGI_PORT=${LUIGI_PORT}

networks:
  default:
    driver: bridge
